version: '3.8'

services:
  backend:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=1234
    depends_on:
      - mysql

  frontend:
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - api

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sgg
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  zabbix:
    image: zabbix/zabbix-server-mysql:latest
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zzzz
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - mysql

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    ports:
      - "8080:8080"
    environment:
      ZBX_SERVER_HOST: zabbix
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zzzz
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - zabbix
      - mysql
